import type { Metadata } from "next";
import "./globals.css";
import Header from '@/app/components/Header/Header';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        <div className="page w-full min-h-screen bg-light text-darkGray dark:bg-darkGray dark:text-light">
          <Header />  

              {children}

        </div>
      </body>
    </html>
  );
}
